import Head from "next/head";
import Footer from "@/components/Footer";
import TemplateLogin from "@/template/Login";

export default function Login() {
    return (<>
        <Head>
            <title>Pandêmico - Login</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="assets/img/pandemic.png" />
        </Head>
        <TemplateLogin/>
    </>
    )
}