import Head from "next/head";
import Footer from "@/components/Footer";
import * as S from "./styles"
import * as Yup from "yup";
import { Formik} from "formik";
import { Input } from "@mui/material";

export default function TemplateLogin() {

    const ValidationSchema = Yup.object().shape({
        email: Yup.string().email("Adicione um email válido").required("Campo obrigatório"),
        password: Yup.string().required("Campo obrigatório"),
    })

    return (
    <>
        <Head>
            <title>Pandêmico - Login</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="assets/img/pandemic.png" />
        </Head> 
            <S.Title>Pandêmico</S.Title>
            <S.Container>
                <S.Img src="/assets/img/pandemic.png"/>
                <S.SubTitle>Seja Bem-vindo a família!</S.SubTitle>
                <Formik 
                initialValues={{
                    email:'',
                    password:'',
                    }}
                     onSubmit={()=>{}}
                     validationSchema={ValidationSchema}>
                        {({ values, errors,touched, handleChange, handleBlur, handleSubmit}) => (
                            <S.ContainerForm>
                               <S.ContainerInput>
                                    <S.Label>E-mail</S.Label>
                                    <Input
                                    placeholder="E-mail"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.email}
                                    />
                                </S.ContainerInput>
                                <S.ContainerInput>
                                    <S.Label>Password</S.Label>
                                    <Input
                                    placeholder="Password"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.password}
                                    />
                                </S.ContainerInput>
                                <S.ContainerButton>
                                    <S.ButtonForm>Entrar</S.ButtonForm>
                                </S.ContainerButton>
                            </S.ContainerForm>
                        )}
                </Formik>
                    <S.ContainerRegister>
                        <S.A href="#">Ainda não é cadastrado em nossa plataforma? acesse
                            agora e faça o seu cadastro.
                        </S.A>
                    </S.ContainerRegister>
            </S.Container>
        <Footer />
    </>
    )
}